### ISSUE TITLE
<style> is leftover

### ISSUE THREAD

**Issue by sampotts** [ryanmorr/is-selector-supported#1]
Hey Ryan,

Really handy little script but one of the guys here noticed we were left with `<style></style>` in the `<head>` after using it. I think it just needs the following added at the end of the `try` and `catch` before the return statements: 

```javascript
head.removeChild(style);
```

Cheers

**Comment by ryanmorr** [comment]
That style element is actually re-used for every invocation of the `isSelectorSupported` function rather than creating and destroying it for every call which would be unnecessary overhead.

**Comment by sampotts** [comment]
Ah yes, we'd edited your snippet to encapsulate the whole thing into a function so we can do the above fix as we re-create every time to keep the DOM clean. No worries.
